import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import React,{useEffect} from 'react'
//importar firebase
import firebaseApp1 from '../firebase'
import {getFirestore, collection, addDoc, getDocs, doc, deleteDoc, getDoc, setDoc} from 'firebase/firestore'
import { async } from '@firebase/util'
const db = getFirestore(firebaseApp1)


import {useRouter} from 'next/router'


export default function Home({Despesas}) {
  

  const router = useRouter()
  

  return (
    <Layout className={styles.container}>
      <Head>
        <title>FINAN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <div className="container">
        <Link href="/formulario">
          <a><button className='btn btn-primary mb-4'>Incluir produtoo</button></a>
        </Link>
   
        <table class="table">
  <thead>
    <tr>
      <th scope="col">Desccrição</th>
      <th scope="col">Mês</th>
      <th scope="col">Ano</th>
      <th scope="col">Valor</th>
    </tr>
  </thead>
 
  <tbody>

 
  {Despesas.map((Despesa) => (
    
    <tr>
      
      <th >{Despesa.nome}</th>
      <td>{Despesa.Mes}</td>
      <td>{Despesa.Ano}</td>
      <td>{Despesa.Valor}</td> 
      <button className='btn btn-danger' onClick={()=>router.push(`/despesa/${Despesa.id}`)} >View</button>
    </tr>
 
   
 ))}
 
  </tbody>
 
</table>
        </div>

     
    </Layout>
  )
}

//EXIBIR LISTA
  export const getServerSideProps = async(context)=>{
    const querySnapshot = await getDocs(collection(db,'Despesa'))
                  const docs = []
                  querySnapshot.forEach((doc)=>{
                      docs.push({...doc.data(), id: doc.id})
                  })
  
    return {
      props:{
        Despesas: docs
      }
    }
  }
